### ISSUE TITLE
有问题反馈

### ISSUE THREAD

**Issue by qa12587** [15dd/wenku8reader#1]
个人感觉小说页面和评论区这些横线没必要留着，还有加上这个颜色页面整体不协调。还有一个有些收藏的小说封面不显示，没想到找这么久终于有好的第三方了
https://ibb.co/Fn4My5W
https://ibb.co/9Y90sPH

**Comment by 15dd** [comment]
一般情况下，我不会去改动ui了。封面不显示的问题，我已在v1.0.1版本中修复了
