### ISSUE TITLE
页面逻辑bug

### ISSUE THREAD

**Issue by GUAN-XP** [15dd/wenku8reader#13]
在非首页的页面横屏再恢复竖屏后会显示首页内容，而不是原先的内容，百分百复现

**Comment by 15dd** [comment]
确实是这样的，我没有在activity的onDestory()方法中保存当前页面的一些操作信息，在横竖屏切换时，软件直接重建了activity，也就是你说的“在非首页的页面横屏再恢复竖屏后会显示首页内容，而不是原先的内容”。
而且，我并没有给软件做过横屏优化，干嘛要横屏。
我考虑在后期的版本更新中给软件强制竖屏。

**Comment by 15dd** [comment]
已于v2.3.0中修复
