### ISSUE TITLE
网络超时

### ISSUE THREAD

**Issue by kinhaiyue** [15dd/wenku8reader#15]
手机华为HUAWEI nova 7pro，软件版本2.2.1。
网络正常且能打开文库网页。进入软件主页面也没有问题，但是点开小说就会条网络超时，挂梯子也没有用
![Screenshot_20231026_153009_com cyh128 wenku8reader](https://github.com/15dd/wenku8reader/assets/149048942/81d87211-ffc5-4a05-8d1a-da0190ce5fc3)

**Comment by 15dd** [comment]
确实有这个问题，不过我最近没什么时间修了，我周六再看看吧

**Comment by 15dd** [comment]
我找到问题了，但是我现在没时间修复它了，我会在寒假的时候再修复它

**Comment by kinhaiyue** [comment]
辛苦了大佬

**Comment by 7tyzh** [comment]
> 我找到问题了，但是我现在没时间修复它了，我会在寒假的时候再修复它

收到

**Comment by 15dd** [comment]
已在v2.2.2中修复
