### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by Umasou4765** [15dd/wenku8reader#17]
![Screenshot_2023-11-20-19-20-15-23_dd777e090bb38d807f3ec36df8f2d83f](https://github.com/15dd/wenku8reader/assets/86976137/5308df46-c226-4f09-b65c-faab7254d42a)
![Screenshot_2023-11-20-19-20-05-25_dd777e090bb38d807f3ec36df8f2d83f](https://github.com/15dd/wenku8reader/assets/86976137/56e3afcd-51f0-4304-a432-73b113a52cb3)
![Screenshot_2023-11-20-19-20-07-67_dd777e090bb38d807f3ec36df8f2d83f](https://github.com/15dd/wenku8reader/assets/86976137/cdc47c0a-bd38-4467-947b-fa96f8db5587)

**Comment by 15dd** [comment]
你确定网络环境没问题吗？我刚刚试了一下，软件能正常使用，没有问题

**Comment by Umasou4765** [comment]
我可以正常打开这个网页https://www.wenku8.cc/index.php

**Comment by 15dd** [comment]
![Screenshot_2023-11-20-19-42-03-795_com.cyh128.wenku8reader.jpg](https://github.com/15dd/wenku8reader/assets/69246156/006d825f-3406-4d16-b19c-683d9f93d315)

我这边复现不了这个情况，软件能正常使用，所以我也不知道怎么回事

**Comment by Umasou4765** [comment]
测出原因了，我是海外的，使用了中国vpn就可以了，打扰了

**Comment by Umasou4765** [comment]
之前用过其他的应用可以直连，这是锁区了吗？

**Comment by 15dd** [comment]
确实是锁区了，wenku8官方只允许中国ip访问网站
