### ISSUE TITLE
阅读器正文右对齐

### ISSUE THREAD

**Issue by yuduotianguang** [15dd/wenku8reader#19]

**Comment by 15dd** [comment]
右边对齐什么？我没太懂你的意思。

**Comment by yuduotianguang** [comment]
> 右边对齐什么？我没太懂你的意思。

文字右对齐

**Comment by 15dd** [comment]
一般情况下，小说内容都是左对齐的。为什么要右对齐？

**Comment by yuduotianguang** [comment]
> 一般情况下，小说内容都是左对齐的。为什么要右对齐？
同时对齐啊

**Comment by 15dd** [comment]
意思是让右下角的那个提示一起左对齐？（图片中的红框区域）
<br>
![IMG_20240207_150001](https://github.com/15dd/wenku8reader/assets/69246156/bcf1903d-36e0-436f-b243-2484f42c589e)

**Comment by yuduotianguang** [comment]
像这样正文两端都对齐




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "15dd/wenku8reader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月7日(星期三) 下午3:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [15dd/wenku8reader] 阅读器右边是否也可以对齐，强迫症有点难受 (Issue #19)





 
意思是让右下角的那个提示一起左对齐？（图片中的红框区域）
 

 IMG_20240207_150001.jpg (view on web)

**Comment by 15dd** [comment]
像哪样？你是不是少发东西了？你可以发图片示意一下

**Comment by yuduotianguang** [comment]
![QQ图片20240207153542](https://github.com/15dd/wenku8reader/assets/104707441/1a6df694-ef24-4adc-b624-bcd4b7f89dfa)
之前是QQ邮箱发的附带照片（

**Comment by 15dd** [comment]
这样如何？
![Screenshot_2024-08-07-15-26-50-377_com.cyh128.hikarinovel.jpg](https://github.com/user-attachments/assets/0b29878f-bb0d-4511-aafa-b86415a6d6c5)

**Comment by yuduotianguang** [comment]
> 这样如何？
> ![Screenshot_2024-08-07-15-26-50-377_com.cyh128.hikarinovel.jpg](https://github.com/user-attachments/assets/0b29878f-bb0d-4511-aafa-b86415a6d6c5)
> 

差不多了，只不过像逗号这种标点还是不要出现在开头吧

**Comment by 15dd** [comment]
水平有限，只能做到这种程度了
