### ISSUE TITLE
tag页面显示问题

### ISSUE THREAD

**Issue by GUANXINPENG** [15dd/wenku8reader#2]
![Screenshot_2023-06-19-12-18-38-33_dd777e090bb38d807f3ec36df8f2d83f](https://github.com/15dd/wenku8reader/assets/89452691/645ccbfb-182a-4ed9-98d1-e773f8126395)
版本号1.0.2
手机型号：findx6 安卓13
分辨率 1240*2772

**Comment by 15dd** [comment]
下一个版本修复

**Comment by 15dd** [comment]
该问题会在下一个版本修复

**Comment by 15dd** [comment]
该问题已在1.0.3版本中修复
