### ISSUE TITLE
希望给阅读时的翻页增加一个上下滚动的模式

### ISSUE THREAD

**Issue by sphinx18079** [15dd/wenku8reader#23]
现有的上下翻页每次都是一整页，不能按自己想要的进行滚动调整

**Comment by 15dd** [comment]
更多-设置-选择老阅读器
老阅读器就是上下滚动的阅读方式
![IMG_20240606_171348.jpg](https://github.com/15dd/wenku8reader/assets/69246156/29daabfa-8188-4319-bc2f-dcde2dcad6d4)
