### ISSUE TITLE
請問如果是非中國IP 就不能用嗎？

### ISSUE THREAD

**Issue by NeKoOuO** [15dd/wenku8reader#25]
由於網站是可以正常訪問的 所以我想應該是軟體的問題

**Comment by 15dd** [comment]
也不一定，只是我优先照顾中国大陆的用户，为了方便我才这么说的，不然到时候又一堆人来问我为什么用不了软件

**Comment by NeKoOuO** [comment]
有什麼解決方法嗎

**Comment by 15dd** [comment]
？软件本身并不限制你的ip，主要是wenku8那边限制，目前已知的是日本ip无法使用，只要你的网络能访问wenku8，那么软件也能用

**Comment by NeKoOuO** [comment]
好像可以了 好奇怪

**Comment by NeKoOuO** [comment]
順帶問一下作者目前的重構進度如何了😌

**Comment by 15dd** [comment]
估计再几个月吧，现在还有一些功能没做好
