### ISSUE TITLE
[Bug]: 平板装轻小说文库，关于看不到检查更新和github按键

### ISSUE THREAD

**Issue by Qing-Novel** [15dd/wenku8reader#26]
### 检查单

- [X] 我已确认网络环境没有问题
- [X] 我已确认ip属地为中国大陆

### Bug描述

平板装轻小说文库，关于看不到检查更新和github按键
![Screenshot_20240924_121218_com cyh128 wenku8reader](https://github.com/user-attachments/assets/b35f3e48-ed6f-4942-9922-f228d54b72ef)

https://github.com/user-attachments/assets/3d2f3f81-9c9d-4495-b228-d9882a5907d2

### 安卓版本

安卓10

### 轻小说文库版本

2.3.3

**Comment by 15dd** [comment]
很正常，我没给平板做适配，我暂时没有适配平板的打算

**Comment by Qing-Novel** [comment]
> 很正常，我没给平板做适配，我暂时没有适配平板的打算

好吧。。。不过我平板用到现在貌似就这问题，因为我是小平板所以也不涉及到横屏
