### ISSUE TITLE
[Feature]: 请求添加TTS功能 Request to add TTS functionality

### ISSUE THREAD

**Issue by Gholts** [15dd/wenku8reader#28]
### 检查单

- [X] 我已确认软件内没有此功能
- [X] 我已确认当前issue列表没有相似的请求

### 添加 TTS 功能

- 支援离线 Microsoft TTS, Google TTS 或讯飞 TTS
- 支援调整语速和 TTS 声音配置

### Add TTS function

- Support offline Microsoft TTS, Google TTS or iFlytek TTS
- Supports adjusting speech rate and TTS sound configuration

谢谢 Thanks

**Comment by 15dd** [comment]
暂不考虑
