### ISSUE TITLE
书架界面

### ISSUE THREAD

**Issue by 149898400** [15dd/wenku8reader#3]
希望能有像笔趣阁这样的三列书架![Screenshot_2023-06-23-14-35-28-655_bqg.haita.nuia.guge.jpg](https://github.com/15dd/wenku8reader/assets/102473535/cb18eba9-49ee-427f-a902-7eb6a8b5d621)

**Comment by hz1235** [comment]
慢慢来吧希望后续能自定义阅读背景，字体，排版这些东西

**Comment by 15dd** [comment]
已在1.1.0版本中添加
