### ISSUE TITLE
3.0.0版本首页推荐的下拉刷新没了

### ISSUE THREAD

**Issue by Qing-Novel** [15dd/wenku8reader#32]
偶尔会因为王阔网络问题加载不出来东西，老版本的下拉刷新就方便刷新页面，现在就只能切到别的模块再切回来，或者只能重启软件

**Comment by 15dd** [comment]
正常，推荐那一块我没有做下拉刷新

**Comment by Qing-Novel** [comment]
> 正常，推荐那一块我没有做下拉刷新

那之后会加下拉刷新吗？

**Comment by 15dd** [comment]
刚花了3分钟的时间加上了，之后会更新

**Comment by Qing-Novel** [comment]
> 刚花了3分钟的时间加上了，之后会更新

辛苦作者了
