### ISSUE TITLE
今天晚上3.1打不开了

### ISSUE THREAD

**Issue by Natsuki2005** [15dd/wenku8reader#37]
软件宕机

**Comment by Natsuki2005** [comment]
![Screenshot_20241013_232934_com_cyh128_hikari_novel_CrashActivity](https://github.com/user-attachments/assets/ef69d3d5-f5c6-4101-9ad8-ef3924759f49)
![Screenshot_20241013_232926_com_cyh128_hikari_novel_CrashActivity](https://github.com/user-attachments/assets/e7b848f6-a55c-49a5-9a62-c4c987230ec5)
![Screenshot_20241013_232931_com_cyh128_hikari_novel_CrashActivity](https://github.com/user-attachments/assets/ea73fd74-cd6d-45cf-bcd0-94c1dc9e3c31)

**Comment by 15dd** [comment]
别急，我也打不开了。
暂时先把软件的语言切换成简体中文吧。

**Comment by Natsuki2005** [comment]
> 别急，我也打不开了。 暂时先把软件的语言切换成简体中文吧。

woc，调成简中之后就能用了

**Comment by Natsuki2005** [comment]
> 别急，我也打不开了。 暂时先把软件的语言切换成简体中文吧。

顺便，大佬有B站号吗，我关注一下😃

**Comment by 15dd** [comment]
不用关注了

**Comment by 15dd** [comment]
你现在看看，应该没问题了。好像是wenku8服务器的问题

**Comment by Natsuki2005** [comment]
> 你现在看看，应该没问题了。好像是wenku8服务器的问题

昨天听你的把语言调回简中就能看了

**Comment by 15dd** [comment]
不是，我是说繁体中文
