### ISSUE TITLE
请问有考虑适配大屏设备吗

### ISSUE THREAD

**Issue by LiuHaoUltra** [15dd/wenku8reader#39]
现版本在平板横屏状态下使用时，无论是哪种阅读界面，显示利用率都较低，
请问有考虑增加如图的阅读界面吗
![IMG_20241105_171110_598](https://github.com/user-attachments/assets/8047bd75-00d4-4e94-98ad-bd0022c6103f)

**Comment by 15dd** [comment]
概率很低

**Comment by LiuHaoUltra** [comment]
好的，感谢解答
