### ISSUE TITLE
1.0.3升级至1.1.0版本启动即闪退

### ISSUE THREAD

**Issue by GUANXINPENG** [15dd/wenku8reader#4]
版本号1.1.0
手机型号：findx6 ColorOS 13.1
手动清除数据无效，排查后发现删除Android/data目录下com.cyh128.wenku8reader文件夹后正常启动

**Comment by 15dd** [comment]
正常，这个版本(1.1.0)我在数据库内添加了一些项目，因为1.1.0的数据库项目与老版本1.0.3的数据库项目不匹配，而数据库又是保存在本地的，升级后会继续使用1.0.3的数据库，而不是1.1.0所需的数据库，所以导致闪退。
刚才提到数据库是保存在本地的，所以把软件的本地数据删了就行了，卸载重新安装也可以。
我打算在下一个版本解决这个因数据库项目不一致导致软件升级就闪退的问题。
