### ISSUE TITLE
在mumu模拟器12打开后，无响应

### ISSUE THREAD

**Issue by sink-er** [15dd/wenku8reader#40]
在mumu模拟器12打开后，只显示这个界面，无任何响应，咋回事
![PixPin_2024-11-12_20-45-25](https://github.com/user-attachments/assets/889adc3e-c281-4297-ba36-2508a20b48b6)

**Comment by 15dd** [comment]
你模拟器窗口大小的问题，下面还有内容的。还有，软件我只适配了手机的竖屏模式

**Comment by 15dd** [comment]
你手机上用应该是没有问题的
