### ISSUE TITLE
报告BUG

### ISSUE THREAD

**Issue by N8644** [15dd/wenku8reader#41]
搜索页面和分类页面出现了崩溃，望修复。还有个建议，可以加个仿真翻页吗？
![Screenshot_20241114_205054_com cyh128 hikari_novel](https://github.com/user-attachments/assets/56e0ee19-0852-48c7-a152-42356b9d999d)

**Comment by 15dd** [comment]
第一个，你先回一下tg群的消息。
第二个，不考虑做仿真
