### ISSUE TITLE
登录界面点击登录后按钮错位

### ISSUE THREAD

**Issue by GUANXINPENG** [15dd/wenku8reader#5]
https://github.com/15dd/wenku8reader/assets/89452691/f8cc100a-c6f8-4cef-b930-f33228a9790d

版本号1.1.0
手机型号：findx6 coloros13.1
分辨率 1240*2772
如视频中所示

**Comment by 15dd** [comment]
奇了怪了，我的就没问题，型号是红米k60。
这个问题也等下个版本更新修复。

https://github.com/15dd/wenku8reader/assets/69246156/3151ebef-ed13-4e64-abf2-22bd3f256a46

**Comment by 15dd** [comment]
最新版发了，看看还有没有这个问题

**Comment by GUANXINPENG** [comment]
OK了
