### ISSUE TITLE
改善界面

### ISSUE THREAD

**Issue by bzbzbmn** [15dd/wenku8reader#7]
![IMG_20230716_235558](https://github.com/15dd/wenku8reader/assets/99601367/ceb860e2-9bf9-4e0d-84a6-e9e9df384142)
感觉有点大

**Comment by 15dd** [comment]
你的手机分辨率和ppi比较小，我的不这样，考虑后续优化一下
![Screenshot_2023-07-17-00-06-35-864_com cyh128 wenku8reader](https://github.com/15dd/wenku8reader/assets/69246156/b740862c-cf06-41a4-b1f0-7896750a6f7c)

**Comment by 15dd** [comment]
1.2.0版本发布了，你看看还有没有这个问题

**Comment by bzbzbmn** [comment]
> 1.2.0版本发布了，你看看还有没有这个问题

OK啦，很完美
