### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by zst-z** [15dd/wenku8reader#8]
希望加入文本阅读界面左右滑动切换章节功能。
同时希望优化文本阅读界面点击唤出面板时的文本位置，唤出面板后文本会上移，需要我在次寻找我看到哪里了。会干扰阅读。

**Comment by zst-z** [comment]
![Screenshot_20230723-210750_轻小说文库.png](https://github.com/15dd/wenku8reader/assets/64670945/f72d35a4-c370-49c1-9fe5-8bf163a4e47a)

![Screenshot_20230723-210753_轻小说文库.png](https://github.com/15dd/wenku8reader/assets/64670945/43e11194-ce6a-4eb8-a8f6-c92b10c0223a)

无法选中文本，所以比较难看出我的第二个需求。不过我的记忆好像出错了。唤出界面后文本下移了。

**Comment by 15dd** [comment]
第一个，可以考虑，到时候会加一个开关来开启左右滑动切换章节这个功能。
第二个，这个问题我很早就发现了，我自己也觉得影响阅读，但那个时候想不出什么解决办法，但最近已经有点解决办法了，下个版本应该就能修复。

**Comment by 15dd** [comment]
2.0.0版本已发布
